package com.microsoft.surface.battery;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class mipmap {
        public static final int doc = 0x7f010000;
        public static final int docwhiteicon = 0x7f010001;
    }

    public static final class string {
        public static final int app_name = 0x7f020000;
        public static final int smartcharging_setting = 0x7f020001;
    }
}